version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14.15

commands:
  resolve-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-{{ .Branch }}-
            - v1-yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  lint:
    executor: default

    steps:
      - checkout

      - resolve-dependencies

      - run:
          name: Run ESLint
          command: yarn eslint --format junit --output-file ./reports/junit/eslint-results.xml

      - store_test_results:
          path: ./reports/junit

  unit-test:
    executor: default

    steps:
      - checkout

      - resolve-dependencies

      - run:
          name: Run Unit Test
          command: yarn test --ci --coverage --testResultsProcessor=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit
            JEST_JUNIT_OUTPUT_NAME: unit-test-results.xml

      - store_test_results:
          path: ./reports/junit

      - store_artifacts:
          path: ./coverage

  e2e-test:
    executor: default

    steps:
      - run:
          name: Run E2E Test
          command: echo E2E Test

  build:
    executor: default

    steps:
      - run:
          name: Run Build
          command: echo Build

  deploy:
    executor: default

    steps:
      - run:
          name: Run Deploy
          command: echo Deploy

workflows:
  version: 2

  main:
    jobs:
      - lint

      - unit-test:
          requires:
            - lint

      - build:
          requires:
            - unit-test

      - e2e-test:
          requires:
            - build

      - deploy:
          requires:
            - e2e-test
