version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14.15

commands:
  resolve-dependencies:
    steps:
      - run: ls -al
      - restore_cache:
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-{{ .Branch }}-
            - v1-yarn-packages-

      - run: ls -al

      - run:
          name: Install Dependencies
          command: |
            if [ ! -e ./node_modules ]; then
              yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
            fi

      - run: ls -al

      - save_cache:
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  lint:
    executor: default

    steps:
      - checkout

      - resolve-dependencies

      - run:
          name: Run Linting
          command: yarn lint

  unit-test:
    executor: default

    steps:
      - checkout

      - resolve-dependencies

      - run:
          name: Run Unit Testing
          command: yarn test --coverage

      - store_test_results:
          path: ./coverage

      - store_artifacts:
          path: ./coverage

  e2e-test:
    executor: default

    steps:
      - run:
          name: Run E2E Testing
          command: echo E2E Test

  build:
    executor: default

    steps:
      - run:
          name: Run Building
          command: echo Build

  deploy:
    executor: default

    steps:
      - run:
          name: Run Deploying
          command: echo Deploy

workflows:
  version: 2

  main:
    jobs:
      - lint

      - unit-test:
          requires:
            - lint

      - build:
          requires:
            - unit-test

      - e2e-test:
          requires:
            - build

      - deploy:
          requires:
            - e2e-test
